[tool.poetry]
name = "temp-project"
version = "0.1.0"
description = ""
authors = ["Chaeyoung714 <202102760@hufs.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
