# Generated by Django 4.2.1 on 2023-07-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=100)),
                ('title_eng', models.CharField(max_length=100)),
                ('poster_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('image_url', models.CharField(max_length=256, null=True)),
                ('movie_id', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.movielist')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=100, null=True)),
                ('title_eng', models.CharField(max_length=100, null=True)),
                ('poster_url', models.CharField(max_length=256, null=True)),
                ('rating_aud', models.CharField(max_length=100, null=True)),
                ('rating_cri', models.CharField(max_length=100, null=True)),
                ('rating_net', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('showtimes', models.CharField(max_length=100, null=True)),
                ('release_date', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(default='')),
                ('staffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.staff')),
            ],
        ),
    ]
