# Generated by Django 4.2.3 on 2023-07-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_alter_staff_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielist',
            name='rate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielist',
            name='rating_aud',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielist',
            name='rating_cri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielist',
            name='rating_net',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielist',
            name='release_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielist',
            name='showtimes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielist',
            name='staffs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.staff'),
        ),
        migrations.AddField(
            model_name='movielist',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
