# Generated by Django 4.2.3 on 2023-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_movielist_genre_movielist_rate_movielist_rating_aud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='staffs',
        ),
        migrations.AddField(
            model_name='movielist',
            name='staffs',
            field=models.ManyToManyField(to='board.staff'),
        ),
    ]
