# Generated by Django 4.2.3 on 2023-07-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_staff_movie_id_remove_movielist_staffs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedetail',
            old_name='staffs',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='movielist',
            old_name='staffs',
            new_name='staff',
        ),
    ]
