# Generated by Django 4.2.3 on 2023-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_staffs_moviedetail_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='staff',
            field=models.ManyToManyField(blank=True, to='board.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.TextField(default=''),
        ),
    ]
