# Generated by Django 4.2.3 on 2023-07-15 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_movielist_staff_alter_staff_image_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieDetail',
        ),
    ]
